# 4.8 Grouping Data and Aggregating Variables

1. Aggregating data with agg() function
2. Aggregating data with transform()
3. Deriving columns with loc()

In [1]:
#import libraries
import pandas as pd
import numpy as np
import os

In [2]:
# Path
path = r"C:\Users\Natalia\Documents\Instacart Basket Analysis"

In [3]:
#import ords_prods_merged dataset
df_ords_prods_merge = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'merged_new_variables.pkl'))

Create a subset of the first one million entries in dataframe

In [4]:
#create subset of first one million entries
df = df_ords_prods_merge[:1000000]

print('Sample output of filter of df_ords_prods_merged:')
df.sample(5)

Sample output of filter of df_ords_prods_merged:

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
551551,2216621,38523,12,1,9,21.0,49235,5,1,both,Organic Half & Half,53,16,1.8,Low_range product,Regularly busy,Busiest days,Most orders
590086,204480,142869,35,3,9,2.0,49235,17,1,both,Organic Half & Half,53,16,1.8,Low_range product,Regularly busy,Slowest days,Most orders
354773,1661839,158542,29,0,14,13.0,13176,8,1,both,Bag of Organic Bananas,24,4,10.3,Mid-range product,Busiest day,Busiest days,Most orders
470506,3037178,163313,3,2,12,30.0,30450,16,0,both,Creamy Almond Butter,88,13,3.2,Low_range product,Regularly busy,Regularly busy,Most orders
430549,2802515,199337,36,4,10,2.0,13176,6,1,both,Bag of Organic Bananas,24,4,10.3,Mid-range product,Least busy,Slowest days,Most orders

In [5]:
df.shape

(1000000, 18)

## 1. Grouping Data with agg() function

In [6]:
#group your data by product name 
df.groupby('product_name')

Calculating the mean of the 'order_number' grouped by 'department_id'

In [7]:
#split the data into groups based on dep_id, then agg() by ord_number
df.groupby('department_id').agg({'order_number': ['mean']})

print('Mean')

Mean

In [8]:
#using the mean() function
df.groupby('department_id')['order_number'].mean()

department_id
4     18.825780
7     17.472355
13    17.993423
14    19.246334
16    19.463012
17    11.294069
19    19.305237
20    17.599636
Name: order_number, dtype: float64

In [9]:
#Performing multiple aggregations

print('The mean, min, and max of order number grouped by the department_id:')
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

The mean, min, and max of order number grouped by the department_id:

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

## 2. Aggregating Data with Transform

In [10]:
df_ords_prods_merge['max_order'] = df_ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [11]:
#function to display all rows
pd.options.display.max_rows = None

In [12]:
df.head(100)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
1,2398795,1,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average orders
2,473747,1,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
3,2254736,1,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average orders
4,431534,1,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
5,3367565,1,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
6,550135,1,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
7,3108588,1,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
8,2295261,1,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
9,2550362,1,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average orders
10,2968173,15,15,1,9,7.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
11,1870022,15,17,2,16,8.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
12,1911383,15,18,2,11,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
13,2715276,15,21,1,9,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
14,487368,15,22,1,10,14.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
15,2293453,19,2,5,14,6.0,196,3,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
16,1973799,19,5,6,12,8.0,196,15,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
17,532817,19,7,4,17,6.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average orders
18,1573906,21,10,3,10,6.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
19,1593000,31,10,3,8,7.0,196,17,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average orders
20,2231262,31,17,3,11,8.0,196,14,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
21,2580647,43,6,4,16,4.0,196,9,0,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
22,2187180,43,9,4,12,3.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
23,2497897,52,1,1,9,NaN,196,4,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
24,1318871,52,2,1,10,7.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
25,1261384,52,3,1,10,7.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
26,580568,52,5,2,10,8.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
27,2428073,52,7,2,7,8.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
28,342306,52,9,1,11,7.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
29,1520353,52,10,2,10,8.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
30,2542086,52,11,2,9,7.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
31,944694,52,12,1,16,6.0,196,7,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
32,1268191,52,15,2,11,8.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
33,1122089,52,17,2,10,6.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
34,1498922,52,18,2,10,14.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
35,180919,52,19,3,8,8.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average orders
36,2695875,52,21,5,10,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
37,3205960,67,1,3,11,NaN,196,1,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
38,970922,67,2,1,15,5.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
39,596585,67,3,1,13,7.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
40,2037087,67,4,2,9,8.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
41,2474111,67,5,3,14,8.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
42,1568481,67,6,3,12,7.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
43,2048527,67,8,2,11,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
44,2389031,67,9,2,14,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
45,2378562,67,10,1,10,6.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
46,1515698,67,11,1,11,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
47,1928050,67,12,2,12,8.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
48,1949274,67,13,1,10,6.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
49,551869,67,14,1,9,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
50,768572,67,16,4,10,9.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
51,150528,67,18,5,16,4.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
52,29758,67,19,0,14,9.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most orders
53,1558976,67,21,1,9,5.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
54,863974,67,22,1,11,14.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
55,2308399,67,23,1,14,14.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
56,2759128,81,3,1,9,14.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
57,1812985,81,5,2,20,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
58,1889835,82,1,3,15,NaN,196,6,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
59,499460,82,3,5,10,5.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
60,2728456,82,4,0,11,16.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most orders
61,2653743,82,6,4,9,13.0,196,5,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
62,1358880,82,9,1,10,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
63,343588,82,10,2,11,1.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
64,3034663,82,15,2,11,12.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
65,147262,82,18,1,13,7.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
66,3144004,82,19,2,15,8.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
67,2126069,98,3,0,9,25.0,196,7,0,both,Soda,77,7,9.0,Mid-range product,Busiest day,Busiest days,Most orders
68,2210120,98,7,5,14,5.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
69,681011,98,9,3,9,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
70,2846344,98,11,4,13,15.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
71,747431,98,12,6,13,30.0,196,4,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
72,2383054,98,13,4,11,30.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
73,1993729,98,14,5,8,8.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
74,1403849,109,3,3,17,9.0,196,5,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average orders
75,520620,120,1,3,11,NaN,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
76,3273029,120,3,2,8,19.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
77,1861943,185,2,1,12,25.0,196,10,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
78,2040988,195,1,1,14,NaN,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
79,1680569,195,8,1,9,4.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
80,276171,195,19,5,11,3.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
81,2744976,195,22,5,10,7.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
82,2781919,195,25,1,14,4.0,196,1,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders
83,1738718,195,31,2,8,4.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
84,3058369,195,34,3,10,6.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
85,1485596,195,37,2,15,0.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
86,417035,195,40,3,16,2.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
87,1615297,195,47,5,10,2.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
88,1765587,195,52,3,12,2.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders
89,745908,195,57,4,11,3.0,196,3,1,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
90,2505656,222,17,2,12,1.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
91,3268370,222,38,5,15,1.0,196,6,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
92,2016711,290,9,5,19,6.0,196,8,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
93,2706088,290,28,6,10,7.0,196,16,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
94,1952286,331,6,5,16,30.0,196,8,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
95,3226575,360,1,5,12,NaN,196,1,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Most orders
96,1469869,377,3,5,17,3.0,196,9,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Regularly busy,Average orders
97,1927023,387,2,4,10,22.0,196,3,0,both,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders
98,858092,420,4,1,19,30.0,196,2,0,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Average orders
99,119314,420,5,3,19,16.0,196,2,1,both,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average orders

## 3. Deriving Columns with loc()

In [13]:
#Creating my flag based on values using loc()

In [14]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [15]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 40, 'loyalty_flag'] = 'Regular customer'

In [16]:
df_ords_prods_merge.loc[df_ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [17]:
df_ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: loyalty_flag, dtype: int64

In [18]:
#checking output of certain columns
df_ords_prods_merge[['user_id', 'loyalty_flag', 'max_order']].sample(60)

          user_id      loyalty_flag  max_order
23291547   204743  Regular customer         11
19127863   147752  Regular customer         14
792322     115788    Loyal customer         46
17182638   144005      New customer          6
30494315    21364  Regular customer         30
23988887   152222  Regular customer         11
31873133   185920    Loyal customer         61
8157624     30283  Regular customer         11
3051139    127525  Regular customer         39
25484705   190091  Regular customer         20
30074797    34600  Regular customer         19
10162414   103584      New customer          8
29365802   165534  Regular customer         20
5799306     57731  Regular customer         14
1006666    184451    Loyal customer         99
30850480    29774    Loyal customer         55
1148053    201282  Regular customer         21
7515800     44147  Regular customer         11
1500066    132167    Loyal customer         51
23241350   161386      New customer          7
27263805   179691      New customer         10
15591176   136447  Regular customer         29
29998856   153479  Regular customer         34
537834     195182    Loyal customer         99
20272334   127936  Regular customer         17
32046249   138278  Regular customer         40
8347376     18714      New customer          3
1951127    184334  Regular customer         27
2638645    124240  Regular customer         17
21525067   167622  Regular customer         14
887666      82921      New customer          6
19521640    19102    Loyal customer         58
13215540   134108    Loyal customer         44
32386263    84805  Regular customer         14
21710234     8126  Regular customer         13
14630397   169989  Regular customer         39
12053102   111829    Loyal customer         43
10683023    11964    Loyal customer         54
23722911   152797    Loyal customer         54
17832307   178810  Regular customer         19
16150645    91987    Loyal customer         71
17108505   115961    Loyal customer         55
24579181   137435    Loyal customer         47
14040503   191705  Regular customer         15
28389849   195885    Loyal customer         75
14684731    59047      New customer          4
7567068    160973      New customer          9
4056735     78134    Loyal customer         54
32091301   192223  Regular customer         36
4154536    204217  Regular customer         11
20364306    71561  Regular customer         30
32373248   148280    Loyal customer         50
31422692    73136      New customer          4
13510212    69472  Regular customer         13
16672667   126939    Loyal customer         46
26713684   119434    Loyal customer         73
3084584      2663    Loyal customer         76
3379380    178464    Loyal customer         57
8561219     19146  Regular customer         15
6631215    186704    Loyal customer         99